In [ ]:
import numpy as np

**The Basics**

In [ ]:
 # 1D array
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [ ]:
# 2D array
b = np.array([[9.0,8.0,7.0],[6.0,5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# 3D array
c = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
a.shape

(3,)

In [ ]:
# Get Data Type
a.dtype

dtype('int16')

In [ ]:
# Get Size (nr. of Elements)
a.size

3

In [ ]:
# Get Size (nr. of Bytes)
a.itemsize
# // a.nbytes

2

**Accesing/Changing specific element(s), row(s), column(s), etc.**

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1,5] # // a[1,-2]

13

In [ ]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:,0]

array([1, 8])

In [ ]:
# [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
# Changing an element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
a[:,2]=[3,4]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  4 11 12 20 14]]


**Initializing Different Types of Arrays**

In [ ]:
# 0s matrix
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# 1s matrix
np.ones((4,5))
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# The Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number (full_like)
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [ ]:
# Random Decimal nr. between 0&1
np.random.rand(4,2,3)

array([[[0.87834551, 0.26478818, 0.65989593],
        [0.16423931, 0.12825424, 0.3691731 ]],

       [[0.72031858, 0.08148867, 0.35583816],
        [0.72853312, 0.06775219, 0.38027518]],

       [[0.16186494, 0.49148176, 0.54875501],
        [0.66810581, 0.84135587, 0.15721934]],

       [[0.87882646, 0.463389  , 0.15234897],
        [0.90039653, 0.45722009, 0.42388776]]])

In [ ]:
# Random Integer Nr. values
np.random.randint(-4,7,size=(3,3))

array([[ 0, -2,  3],
       [ 0, -2,  5],
       [ 6,  4, -4]])

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)
r2 = np.repeat(arr,3,axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]
